name: CI Pipeline with Trivy and SonarCloud (Auto-config)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Security Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          format: 'table'

  sonarcloud_analysis:
    name: SonarCloud Analysis
    needs: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para SonarCloud

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-generado por GitHub
        run: |
          # Configuración pública (sin secrets)
          SONAR_ORG="your-org-name"  # Reemplaza con tu organización pública
          SONAR_PROJECT="your-project-key"  # Reemplaza con tu clave pública

          if [ -f "pom.xml" ]; then
            mvn -B verify sonar:sonar \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.projectKey=$SONAR_PROJECT \
              -Dsonar.java.source=17
          elif [ -f "build.gradle" ]; then
            ./gradlew sonarqube \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.projectKey=$SONAR_PROJECT \
              -Dsonar.java.source=17
          else
            echo "No build file detected. Skipping SonarCloud analysis."
          fi
