name: CI Pipeline with Trivy and SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Security Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  sonarcloud_analysis:
    name: SonarCloud Analysis
    needs: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-generado por GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Solo necesario si el repo es privado
        with:
          args: >
            -Dsonar.organization=roy-nova
            -Dsonar.projectKey=RoyNova_pruebaAction
            -Dsonar.projectName=pruebaAction
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.source=17
            -Dsonar.sourceEncoding=UTF-8
