name: CI Pipeline with Trivy and SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Security Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  sonarcloud_analysis:
    name: SonarCloud Analysis
    needs: security_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-sonar-

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Auto-generado
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Opcional si usas GitHub App
        run: |
          # Configuración SonarCloud (reemplaza estos valores)
          SONAR_ORG="tu-organizacion"  # Ej: "githubusername"
          SONAR_PROJECT="tu-proyecto"  # Ej: "githubusername_reponame"
          SONAR_HOST="https://sonarcloud.io"

          if [ -f "pom.xml" ]; then
            mvn -B verify \
              org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar \
              -Dsonar.host.url=$SONAR_HOST \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.projectKey=$SONAR_PROJECT \
              -Dsonar.java.source=17 \
              -Dsonar.sourceEncoding=UTF-8
          elif [ -f "build.gradle" ]; then
            ./gradlew sonarqube \
              -Dsonar.host.url=$SONAR_HOST \
              -Dsonar.organization=$SONAR_ORG \
              -Dsonar.projectKey=$SONAR_PROJECT \
              -Dsonar.java.source=17
          else
            echo "No build file detected. Skipping SonarCloud analysis."
          fi
