name: Security Scan & SonarCloud Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy_scan:
    name: Run Trivy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          format: 'table'
          ignore-unfixed: true

  sonarcloud_analysis:
    name: SonarCloud Scan
    needs: trivy_scan  # Espera a que Trivy termine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Token automático
        with:
          args: >
            -Dsonar.organization=roy-nova
            -Dsonar.projectKey=RoyNova_pruebaAction
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.source=17
            -Dsonar.sourceEncoding=UTF-8
